services:
  db:
    image: postgres:13.2
    volumes:
      - ./docker/db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - blog-api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout for each check is 10 seconds
      retries: 5 # Will retry 5 times before reporting the service as unhealthy
      start_period: 10s # Initial startup time before the first check
  # local:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.local
  #   image: blog-api
  #   container_name: blog-api
  #   hostname: blog-api
  #   depends_on:
  #     - db
  #   networks:
  #     - blog-api-network
  #   ports:
  #     - 8080:8080
  #   tty: true
  #   volumes:
  #     - ./app:/app

networks:
  blog-api-network:
    driver: bridge

volumes:
  mysql_data: