version: "3"

services:
  db:
    image: mysql:8.0.43-debian
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=blogs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-api-network
  local:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    image: blog-api
    container_name: blog-api
    hostname: blog-api
    depends_on:
      - db
    networks:
      - blog-api-network
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./app:/app
      - ./config/local.yaml:/config/config.yml

networks:
  blog-api-network:
    driver: bridge

volumes:
  mysql_data: