FROM golang:1.25.0-trixie AS dev

WORKDIR /app

RUN apt-get update && apt-get install -y make sudo

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group} && useradd -u ${uid} -g ${group} -s /bin/sh -m ${user}

RUN chown -R ${user}:${group} /app /go /usr/local/go /usr/local/bin

USER ${uid}:${gid}

CMD ["bash"]

