name: API Test and Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run API Tests
        run: |
          cd api-tests && gotestsum --junitfile report.xml -- ./...
        continue-on-error: true

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: api-tests/report.xml

  allure-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download test result
        uses: actions/download-artifact@v4
        with:
          name: junit-report

      - name: Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          results-dir: api-tests
          report-dir: allure-report
          allure-commandline-version: 2.27.0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
