name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Run tests with coverage
        run: cd app && go test $(go list ./... | grep -v /cmd) -coverprofile=coverage.out

      - name: Show total coverage
        run: cd app && go tool cover -func=coverage.out | grep total

      - name: Generate HTML coverage
        run: cd app && go tool cover -html=coverage.out -o coverage.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/coverage.html
